color0 #111415
color1 #ffb4ab
color2 #73d1ff
color3 #b5cad7
color4 #c8c2ea
color5 #73d1ff
color6 #b5cad7
color7 #e1e2e5
color8 #8a9297
color9 #ffb4ab
color10 #73d1ff
color11 #b5cad7
color12 #c8c2ea
color13 #73d1ff
color14 #b5cad7
color15 #e1e2e5

cursor                #e1e2e5
cursor_text_color     #111415
background            #111415
foreground            #e1e2e5
selection_foreground  #c0c7cd
selection_background  #40484c
active_border_color   #73d1ff
inactive_border_color #40484c
url_color             #73d1ff

active_tab_foreground   #003548
active_tab_background   #73d1ff
inactive_tab_foreground #c0c7cd
inactive_tab_background #40484c
cursor_trail_color      #c0c7cd
