color0 #121316
color1 #ffb4ab
color2 #aec6ff
color3 #bfc6dc
color4 #dfbcdf
color5 #aec6ff
color6 #bfc6dc
color7 #e3e2e6
color8 #8e9099
color9 #ffb4ab
color10 #aec6ff
color11 #bfc6dc
color12 #dfbcdf
color13 #aec6ff
color14 #bfc6dc
color15 #e3e2e6

cursor                #e3e2e6
cursor_text_color     #121316
background            #121316
foreground            #e3e2e6
selection_foreground  #c5c6d0
selection_background  #44474f
active_border_color   #aec6ff
inactive_border_color #44474f
url_color             #aec6ff

active_tab_foreground   #002e6a
active_tab_background   #aec6ff
inactive_tab_foreground #c5c6d0
inactive_tab_background #44474f
cursor_trail_color      #c5c6d0
