color0 #141316
color1 #ffb4ab
color2 #cbbeff
color3 #cac3dc
color4 #eeb8cb
color5 #cbbeff
color6 #cac3dc
color7 #e6e1e6
color8 #938f99
color9 #ffb4ab
color10 #cbbeff
color11 #cac3dc
color12 #eeb8cb
color13 #cbbeff
color14 #cac3dc
color15 #e6e1e6

cursor                #e6e1e6
cursor_text_color     #141316
background            #141316
foreground            #e6e1e6
selection_foreground  #cac4cf
selection_background  #48454e
active_border_color   #cbbeff
inactive_border_color #48454e
url_color             #cbbeff

active_tab_foreground   #332074
active_tab_background   #cbbeff
inactive_tab_foreground #cac4cf
inactive_tab_background #48454e
cursor_trail_color      #cac4cf
